# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rco_finite_size_correction2 <- function(a, p_a, A, extantLines, mstates) {
    invisible(.Call('_phydynR_rco_finite_size_correction2', PACKAGE = 'phydynR', a, p_a, A, extantLines, mstates))
}

eventTimes2extant <- function(eventTimes, nodeheights, parentheights) {
    .Call('_phydynR_eventTimes2extant', PACKAGE = 'phydynR', eventTimes, nodeheights, parentheights)
}

update_alpha0 <- function(pu, pv, F, Y, A) {
    .Call('_phydynR_update_alpha0', PACKAGE = 'phydynR', pu, pv, F, Y, A)
}

update_states0 <- function(mstates, Q) {
    invisible(.Call('_phydynR_update_states0', PACKAGE = 'phydynR', mstates, Q))
}

update_states1 <- function(mstates, Q, extantLines) {
    .Call('_phydynR_update_states1', PACKAGE = 'phydynR', mstates, Q, extantLines)
}

dAL <- function(t, y, parms) {
    .Call('_phydynR_dAL', PACKAGE = 'phydynR', t, y, parms)
}

solvePikL0 <- function(times, Fs, Gs, Ys, h0, h1, pik0, step_size_res) {
    .Call('_phydynR_solvePikL0', PACKAGE = 'phydynR', times, Fs, Gs, Ys, h0, h1, pik0, step_size_res)
}

solvePikL1 <- function(times, Fs, Gs, Ys, h0, h1, pik0, step_size_res) {
    .Call('_phydynR_solvePikL1', PACKAGE = 'phydynR', times, Fs, Gs, Ys, h0, h1, pik0, step_size_res)
}

dQL <- function(x, F, G, Y, A0) {
    .Call('_phydynR_dQL', PACKAGE = 'phydynR', x, F, G, Y, A0)
}

solveQfwd0 <- function(times, Fs, Gs, Ys, deaths, m, h1, h0) {
    .Call('_phydynR_solveQfwd0', PACKAGE = 'phydynR', times, Fs, Gs, Ys, deaths, m, h1, h0)
}

updateWCpp <- function(W, psi_a, utips, vtips, utips_Wcoords, vtips_Wcoords) {
    .Call('_phydynR_updateWCpp', PACKAGE = 'phydynR', W, psi_a, utips, vtips, utips_Wcoords, vtips_Wcoords)
}

sourceAttribMultiDemeCpp2 <- function(heights, Fs, Gs, Ys, eventIndicator, eventIndicatorNode, eventHeights, sampleStates, daughters, n, Nnode, m, AgtYboundaryCondition, maxHeight, step_size_res) {
    .Call('_phydynR_sourceAttribMultiDemeCpp2', PACKAGE = 'phydynR', heights, Fs, Gs, Ys, eventIndicator, eventIndicatorNode, eventHeights, sampleStates, daughters, n, Nnode, m, AgtYboundaryCondition, maxHeight, step_size_res)
}

sourceAttribMultiDemeCpp <- function(heights, Fs, Gs, Ys, eventIndicator, eventIndicatorNode, eventHeights, sampleStates, daughters, n, Nnode, m, AgtYboundaryCondition, maxHeight) {
    .Call('_phydynR_sourceAttribMultiDemeCpp', PACKAGE = 'phydynR', heights, Fs, Gs, Ys, eventIndicator, eventIndicatorNode, eventHeights, sampleStates, daughters, n, Nnode, m, AgtYboundaryCondition, maxHeight)
}

solveQALboost0 <- function(times, Fs, Gs, Ys, h0, h1, L0, A0) {
    .Call('_phydynR_solveQALboost0', PACKAGE = 'phydynR', times, Fs, Gs, Ys, h0, h1, L0, A0)
}

solveQALboost1 <- function(times, Fs, Gs, Ys, h0, h1, L0, A0) {
    .Call('_phydynR_solveQALboost1', PACKAGE = 'phydynR', times, Fs, Gs, Ys, h0, h1, L0, A0)
}

simulateTreeCpp2 <- function(times, Fs, Gs, Ys, As, sortedCoHeights, sortedSampleHeights, sortedSampleStates, maxSampleTime, m, finiteSizeCorrection, DEMES) {
    .Call('_phydynR_simulateTreeCpp2', PACKAGE = 'phydynR', times, Fs, Gs, Ys, As, sortedCoHeights, sortedSampleHeights, sortedSampleStates, maxSampleTime, m, finiteSizeCorrection, DEMES)
}

simulateTreeCpp3x0 <- function(times, Fs, Gs, Ys, sortedSampleHeights, sortedSampleStates, maxSampleTime, m, finiteSizeCorrection, substitutionRates, sequenceLength) {
    .Call('_phydynR_simulateTreeCpp3x0', PACKAGE = 'phydynR', times, Fs, Gs, Ys, sortedSampleHeights, sortedSampleStates, maxSampleTime, m, finiteSizeCorrection, substitutionRates, sequenceLength)
}

